[package]
name = "_9_procmacro_god"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[dependencies]
proc-macro2 = "0.4.24"
quote = "0.6.10"

[dependencies.syn]
features = ["full"]
version = "0.15.23"

[lib]
name = "lib"
proc-macro = true
